### PR TITLE
Remove bashisms from Makefile

### PR DESCRIPTION
**Pull request by bsmith94**
Change double-bracket test to single-bracket.
Change double-equals operator to equals.

### CODE REVIEW

**Comment by mwheinz** [comment]
Why do you feel this is needed?

That is, I haven't seen any environments that still use sh, and this has been in the code for several years.

**Comment by bsmith94** [comment]
> That is, I haven't seen any environments that still use sh, and this has been in the code for several years.

The default shell for make is /bin/sh. This an issue on debian, where the bashisms cause a non-fatal build error, specified in the original post.

https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

**Comment by mwheinz** [comment]
Okay. Thanks for explaining - and for contributing.

I'm not sure this will make the next official release, but I'll try to get it in.

**Comment by bsmith94** [comment]
FWIW, the bashisms work on RHEL because /bin/sh is a symlink to /bin/bash and it accepts bashisms. Debian uses dash as the replacement for /bin/sh.

**Comment by bsmith94** [comment]
Excellent. I have it fixed in the debian package. Forwarding as a courtesy. Thanks.

**Comment by mwheinz** [comment]
This has been folded into our internal builds of PSM2 and will be part of our next github release. Thanks, @bsmith94.

**Pull request closed without merging**
